In [1]:
import numpy as np

### 配列生成

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [15]:
a.dtype

dtype('int64')

In [16]:
a.shape #配列の各次元の要素数

(4, 3)

In [17]:
a.ndim #配列の次元数

2

In [18]:
a.astype(np.float32) #キャスト

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]], dtype=float32)

In [20]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [23]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [34]:
np.linspace(1, 10, 4)

array([  1.,   4.,   7.,  10.])

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
b = a.reshape(2, 5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

### 配列の操作

In [44]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [47]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [49]:
a = np.array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [51]:
a[1:-1]

array([12, 13, 14])

In [54]:
a[-1:1]

array([], dtype=int64)

In [55]:
a[::2]

array([11, 13, 15])

In [56]:
a = np.array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])

In [61]:
a[0, :]

array([0, 1, 2, 3, 4, 5])

In [62]:
a[:, 3]

array([ 3, 13, 23, 33, 43, 53])

In [58]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [60]:
a[1:3, 2:4]

array([[12, 13],
       [22, 23]])

In [63]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [65]:
a = np.arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [66]:
indices = [1, 2, -3]
y = a[indices]
print y

[10 20 50]


In [68]:
mask = np.array([0,1,1,0,0,1,0,0],
            dtype=bool)
a[mask]

array([10, 20, 50])

In [69]:
from numpy.random import rand
a = rand(10)
a

array([ 0.64103436,  0.96414775,  0.68777484,  0.61382683,  0.11804514,
        0.37623495,  0.516858  ,  0.75571465,  0.181585  ,  0.54968717])

In [70]:
mask = a > 0.5
a[mask]

array([ 0.64103436,  0.96414775,  0.68777484,  0.61382683,  0.516858  ,
        0.75571465,  0.54968717])

### 配列の計算

dot: For 2-D arrays it is equivalent to matrix multiplication

In [72]:
np.dot(3, 4)

12

In [73]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [74]:
xlist = np.linspace(-5, 5, 10).reshape(10, 1)
xlist

array([[-5.        ],
       [-3.88888889],
       [-2.77777778],
       [-1.66666667],
       [-0.55555556],
       [ 0.55555556],
       [ 1.66666667],
       [ 2.77777778],
       [ 3.88888889],
       [ 5.        ]])

In [75]:
w1 = np.random.random((4, 2))
w1

array([[ 0.65745702,  0.97220471],
       [ 0.21016709,  0.82995318],
       [ 0.43192508,  0.61277194],
       [ 0.36013696,  0.17299199]])

In [77]:
x = np.array([xlist[1]])
x = np.insert(x, 0, 1)
x

array([ 1.        , -3.88888889])

In [80]:
w = w1[1, :]
print w
a = np.dot(w1[1, :], x)
print a

[ 0.21016709  0.82995318]
-3.0174286093
